//Import section
import {
  // Add constants not generated

  // Read constants not generated

  GET_EMPLOYEES_REQUEST,
  GET_EMPLOYEES_SUCCESS,
  GET_EMPLOYEES_FAILURE,

  EMPLOYEE_UPDATE_REQUEST,
  EMPLOYEE_UPDATE_SUCCESS,
  EMPLOYEE_UPDATE_FAILURE,

  // Deleted constants not generated
} from 'examples/code-example/with-specific-reducers/constants/';

// Reducers change state's section
// Add reducer not generated

// Read reducer not generated

export function getEmployeesRequest() {
  return {
    type: GET_EMPLOYEES_REQUEST,
  };
}

export function getEmployeesSuccess(employees) {
  return {
    type: GET_EMPLOYEES_SUCCESS,
    payload: employees,
  };
}

export function getEmployeesFailure(error) {
  return {
    type: GET_EMPLOYEES_FAILURE,
    payload: error,
  };
}

export function employeeUpdateRequest() {
  return {
    type: EMPLOYEE_UPDATE_REQUEST,
  };
}

export function employeeUpdateSuccess() {
  return {
    type: EMPLOYEE_UPDATE_SUCCESS,
  };
}

export function employeeUpdateFailure(data) {
  return {
    type: EMPLOYEE_UPDATE_FAILURE,
    payload: data,
  };
}

// Delete reducer not generated

// This file was autogenerated by reducer-maker
