//Import section
import {
  USER_ADD_REQUEST,
  USER_ADD_SUCCESS,
  USER_ADD_FAILURE,

  GET_USER_REQUEST,
  GET_USER_SUCCESS,
  GET_USER_FAILURE,

  GET_USERS_REQUEST,
  GET_USERS_SUCCESS,
  GET_USERS_FAILURE,

  USER_UPDATE_REQUEST,
  USER_UPDATE_SUCCESS,
  USER_UPDATE_FAILURE,

  USER_DELETE_REQUEST,
  USER_DELETE_SUCCESS,
  USER_DELETE_FAILURE,
} from 'examples/code-example/with-init-state/constants/';

// Reducers change state's section
export function userAddRequest() {
  return {
    type: USER_ADD_REQUEST,
  };
}

export function userAddSuccess() {
  return {
    type: USER_ADD_SUCCESS,
  };
}

export function userAddFailure(error) {
  return {
    type: {name.toUpperCase()}_ADD_FAILURE,
    payload: error,
  };
}

export function getUserRequest() {
  return {
    type: GET_USER_REQUEST,
  };
}

export function getUserSuccess(user) {
  return {
    type: GET_USER_SUCCESS,
    payload: user,
  };
}

export function getUserFailure(error) {
  return {
    type: GET_USER_FAILURE,
    payload: error,
  };
}

export function getUsersRequest() {
  return {
    type: GET_USERS_REQUEST,
  };
}

export function getUsersSuccess(users) {
  return {
    type: GET_USERS_SUCCESS,
    payload: users,
  };
}

export function getUsersFailure(error) {
  return {
    type: GET_USERS_FAILURE,
    payload: error,
  };
}

export function userUpdateRequest() {
  return {
    type: USER_UPDATE_REQUEST,
  };
}

export function userUpdateSuccess() {
  return {
    type: USER_UPDATE_SUCCESS,
  };
}

export function userUpdateFailure(data) {
  return {
    type: USER_UPDATE_FAILURE,
    payload: data,
  };
}

export function userDeleteRequest() {
  return {
    type: USER_DELETE_REQUEST,
  };
}

export function userDeleteSuccess() {
  return {
    type: USER_DELETE_SUCCESS,
  };
}

export function userDeleteFailure(data) {
  return {
    type: USER_DELETE_FAILURE,
    payload: data,
  };
}

// This file was autogenerated by reducer-maker
