//Import section
import {
  // Add constants not generated

  // Read constants not generated

  GET_EMPLOYEES_REQUEST,
  GET_EMPLOYEES_SUCCESS,
  GET_EMPLOYEES_FAILURE,

  EMPLOYEE_UPDATE_REQUEST,
  EMPLOYEE_UPDATE_SUCCESS,
  EMPLOYEE_UPDATE_FAILURE,

  // Deleted constants not generated

  SET_STATE,
} from 'examples/code-example/with-specific-reducers/constants/';

import InitialState from 'examples/code-example/with-specific-reducers/states//employee-state';

// Main reducer function
export default function employeesReducer(state = InitialState, action) {
  switch (action.type) {
    // Add case not generated

    // Read case not generated

    case GET_EMPLOYEES_REQUEST:
    {
      return {
        ...state,
        isFetching: true,
        error: null,
      };
    }

    case GET_EMPLOYEES_SUCCESS:
    {
      return {
        ...state,
        employees: action.payload.employees,
        isFetching: false,
        error: null,
      };
    }

    case GET_EMPLOYEES_FAILURE:
    {
      return {
        ...state,
        isFetching: false,
        error: action.payload,
        success: null,
      };
    }

    case EMPLOYEE_UPDATE_REQUEST:
    {
      return {
        ...state,
        isFetching: true,
        error: null,
      };
    }

    case EMPLOYEE_UPDATE_SUCCESS:
    {
      return {
        ...state,
        employees: null,
        isFetching: false,
        error: null,
      };
    }

    case EMPLOYEE_UPDATE_FAILURE:
    {
      return {
        ...state,
        isFetching: false,
        error: action.payload,
        success: null,
      };
    }

    // Delete case not generated

    case SET_STATE:
    {
      const {
        employees
      } = JSON.parse(action.payload);

      return {
        ...state,
        disabled: employees.disabled,
        error: employees.disabled,
        isValid: employees.isValid,
        isFetching: employees.isFetching,
        employees: employees.employees
      };
    }

    default:
    {
      return state;
    }
  }
}
// This file was autogenerated by reducer-maker
